blank_issues_enabled: false
contact_links:
  - name: AI Retro Community Support
    url: https://github.com/ai-retro/ai-retro/discussions
    about: Please ask and answer questions here.
  - name: AI Retro Documentation
    url: https://ai-retro.com/docs
    about: Please check out the documentation here.
